#--- VDN specific parameters ---
# Monte Carlo Q_tot Learning
#VDN版本的differ，专用于GRF地图

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode_differ"
scheme: "differ"

buffer_size: 5000


t_max: 2005000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "n_mac"
agent: "n_rnn" 
agent_output_type: "q"
rnn_hidden_dim: 256

learner: "vdn_differ"
mixer: "vdn"
lr: 0.0005 # Learning rate for agents
td_lambda: 1.0
optimizer: 'adam'
gamma: 0.999

# orthogonal init for DNN
use_orthogonal: False
gain: 0.01

# rnn layer normalization
use_layer_norm: False

# Priority experience replay
use_per: False
per_alpha: 0.6
per_beta: 0.4
return_priority: True

#differ特有
selected: "PER_weight"
warm_up: True 
selected_alpha: 0.8
selected_ratio: 0.6
selected_ratio_start: 0.8
selected_ratio_end: 1.0
warm_up_ratio: 0.6

selected_epsilon: 0.01
beta_start: 0.6
beta_end: 1

name: "vdn_differ"
